pipeline {
    agent any

    environment {
        DOCKER_HUB_CREDS = credentials('dockerhub-creds')
        BACKEND_IMAGE = "${DOCKER_HUB_CREDS_USR}/book-backend"
        FRONTEND_IMAGE = "${DOCKER_HUB_CREDS_USR}/book-frontend"
        BUILD_TAG = "${BUILD_NUMBER}" // ensures a new tag every time
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: 'github-creds', url: 'https://github.com/nagapavani23/webapp.git'
            }
        }

        stage('Build Backend Docker Image') {
            steps {
                dir('backend') {
                    sh "docker build -t ${BACKEND_IMAGE}:${BUILD_TAG} ."
                }
            }
        }

        stage('Build Frontend Docker Image') {
            steps {
                dir('frontend') {
                    sh "docker build -t ${FRONTEND_IMAGE}:${BUILD_TAG} ."
                }
            }
        }

        stage('Push Docker Images to DockerHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh """
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push ${BACKEND_IMAGE}:${BUILD_TAG}
                        docker push ${FRONTEND_IMAGE}:${BUILD_TAG}
                    """
                }
            }
        }

        stage('Update Kubernetes Manifests') {
            steps {
                sh """
                    sed -i 's|image: .*/book-backend:.*|image: ${BACKEND_IMAGE}:${BUILD_TAG}|' k8s/backend-deployment.yaml
                    sed -i 's|image: .*/book-frontend:.*|image: ${FRONTEND_IMAGE}:${BUILD_TAG}|' k8s/frontend-deployment.yaml
                """
            }
        }

        stage('Login to Azure & Configure AKS Access') {
            steps {
                withCredentials([string(credentialsId: 'azure-sp-sdk-auth', variable: 'AZURE_CRED')]) {
                    sh '''
                        echo "$AZURE_CRED" > azure.json

                        clientId=$(jq -r .clientId azure.json)
                        clientSecret=$(jq -r .clientSecret azure.json)
                        tenantId=$(jq -r .tenantId azure.json)

                        az login --service-principal \
                                 --username "$clientId" \
                                 --password "$clientSecret" \
                                 --tenant "$tenantId"

                        az aks get-credentials --resource-group pavani --name webapp --overwrite-existing
                    '''
                }
            }
        }

        stage('Deploy to AKS') {
            steps {
                sh '''
                    kubectl apply -f k8s/backend-deployment.yaml
                    kubectl apply -f k8s/frontend-deployment.yaml
                '''
            }
        }

        stage('Force Restart to Pull Fresh Image') {
            steps {
                sh '''
                    kubectl rollout restart deployment/backend
                    kubectl rollout restart deployment/frontend
                '''
            }
        }
    }

    post {
        success {
            echo "✅ Successfully deployed fresh build to AKS!"
        }
        failure {
            echo "❌ Deployment failed!"
        }
    }
}
